### ISSUE TITLE
No v5 tag created

### ISSUE THREAD

**Issue by MatthijsBurgh** [actions/delete-package-versions#138]
You created the v5.0.0 release with the same tag, but you didn't create a v5 tag.

Please create this tag.

**Comment by erickguan** [comment]
I bumped into the same problem. I was expecting to use `actions/delete-package-versions@v5` when I saw `v5.0.0` release. Unfortunately, `v5` tag is not there so actions break.

**Comment by mserajnik** [comment]
Same here.

**Comment by MatthijsBurgh** [comment]
@jidicula could you create the `v5` tag?

**Comment by jidicula** [comment]
Sorry about that! I've just pushed the [`v5` tag](https://github.com/actions/delete-package-versions/releases/tag/v5) 😅
