### ISSUE TITLE
Feature request: Delete specific package version

### ISSUE THREAD

**Issue by orwtech** [actions/delete-package-versions#34]
It would be cool if you could specify the package version number in the package-name like:

package-name:  org.sample.artifact-name@1.0
package-name:  org.sample.artifact-name@latest

And then only that version of the package will be deleted

As it is not all package versions are deleted with the name org.sample.artifact-name

**Comment by sweeguan-ng** [comment]
Would be great if we are able to delete specific version number instead of version ID, as getting the version ID is another difficult part which required the usage of graphQL.
