### ISSUE TITLE
Container Registry Support

### ISSUE THREAD

**Issue by amiantos** [actions/delete-package-versions#35]
Is there a plan to update this action to support container registry, or make a `delete-container-versions` action?

**Comment by thomastvedt** [comment]
And if this action will support container registry in the future, will containers show up under repository.packages in Github's GraphQL API in the future?

This graphql returns NuGet packages, but not Docker images:

```
query getVersions($owner: String!, $repo: String!, $last: Int!) {
    repository(owner: $owner, name: $repo) {
    	name
      packages(first: 10) {
      	totalCount
        edges {
          node {
            name
            versions(last: $last) {
              edges {
                node {
                  id
                  version
                }
              }
            }
          }
        }
      }
    }
  }
```

**Comment by kc1r74p** [comment]
@amiantos  @thomastvedt 
FYI: I created a fix over here:
https://github.com/actions/delete-package-versions/issues/28#issuecomment-804394142

I will see to open a PR into this repo, however for me it depends how the roadmap looks and if the GraphQL API will also deliver this functionality in the future.

**Comment by thomastvedt** [comment]
> @amiantos @thomastvedt
> FYI: I created a fix over here:
> [#28 (comment)](https://github.com/actions/delete-package-versions/issues/28#issuecomment-804394142)
> 
> I will see to open a PR into this repo, however for me it depends how the roadmap looks and if the GraphQL API will also deliver this functionality in the future.

Nice!, if I understand correctly it is now possible to delete container packages from ghcr.io with REST? But still not via graphql yet?

Also, this repository (delete-package-versions) is marked as unmaintained, did you find a good alternative?

**Comment by mr-linch** [comment]
If just need to delete packages by tag, you can checkout our action https://github.com/marketplace/actions/ghcr-delete-image

**Comment by eberkund** [comment]
Any updates on this?

**Comment by hariso** [comment]
I'd be interested in this too.

**Comment by sondrelg** [comment]
https://github.com/snok/container-retention-policy lets you delete GHCR packages 🙂

**Comment by amiantos** [comment]
@sondrelg that action serves my purposes! I am going to close this issue, I consider [that action](https://github.com/snok/container-retention-policy) to have solved it.
