### ISSUE TITLE
 delete-only-pre-release-versions throws Error: query for oldest version failed.

### ISSUE THREAD

**Issue by cat-prices** [actions/delete-package-versions#59]
If there are too many steps in a workflow then it throws an error.

```
Run actions/delete-package-versions@v2.0.0
  with:
    package-name: Package.Name
    min-versions-to-keep: 10
    delete-only-pre-release-versions: true
    num-old-versions-to-delete: 1
    ignore-versions: ^$
    token: ***
(node:1585) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Error: query for oldest version failed. verify input parameters are correct
```

I have 50 packages and noticed that the first five or so always seemed to run successfully, even when I changed the order in which packages were deleted. I have one step per package. 
As a work around, I split the workflow into ten separate workflows, with five steps in each one. They all run successfully when the number of steps/packages is limited to a few per workflow.

**Comment by NamrataJha** [comment]
Hey @codan-prices I am unable to repro this on my side. Can you specify what is the rough amount of versions present in the packages?

**Comment by prices13** [comment]
> Hey @codan-prices I am unable to repro this on my side. Can you specify what is the rough amount of versions present in the packages?

Sorry, totally missed your question. The number of versions varies for each package but it's a large number. Picked one at random and it has 30 versions per page, and 40 pages. So 1200+ per package. That's after it runs and cleans up prerelease pacakges.

**Comment by cat-prices** [comment]
This issue seems to be resolved in v5 so closing this issue
